name       : perl
version    : 5.32.1
release    : 28
homepage   : https://www.perl.org/
source     :
    - https://www.cpan.org/src/5.0/perl-5.32.1.tar.xz : 57cc47c735c8300a8ce2fa0643507b44c4ae59012bfdad0121313db639e02309
license    :
    - Artistic-1.0-Perl
    - GPL-2.0-or-later
    - GPL-1.0-or-later
    - MIT
component  : programming
summary    : Perl
description: |
    An interpreted scripting language, known among some as "Unix's Swiss Army Chainsaw".
builddeps  :
    - bzip2-devel
    - db5-devel
    - gdbm-devel
optimize   : speed
patterns   :
    - docs :
        - /usr/share/man
environment: |
    export BUILD_ZLIB=False
    export BUILD_BZIP2=0
setup      : |
    export versionp=`echo ${version} | sed 's:\.[0-9]$::'`
    export archname="x86_64-linux-thread-multi"

    # Changes to the arch (threading for example), require full rebuilds
    # .x releases no longer require rebuilds (5.yy.x)
    ./Configure -des -Dprefix=/usr \
                     -Dvendorprefix=/usr \
                     -Dprivlib=%libdir%/perl5/${versionp} \
                     -Darchlib=%libdir%/perl5/${versionp}/${archname} \
                     -Dsitelib=%libdir%/perl5/site_perl/${versionp} \
                     -Dsitearch=%libdir%/perl5/site_perl/${versionp}/${archname} \
                     -Dvendorlib=%libdir%/perl5/vendor_perl/${versionp} \
                     -Dvendorarch=%libdir%/perl5/vendor_perl/${versionp}/${archname} \
                     -Dscriptdir=/usr/bin \
                     -Dman1dir=/usr/share/man/man1 \
                     -Dman3dir=/usr/share/man/man3 \
                     -Dpager="/usr/bin/less -isR"  \
                     -Duseshrplib \
                     -Dusethreads \
                     -Adefine:optimize="-O3 -ffunction-sections -fno-semantic-interposition " \
                     -Aappend:optimize="$(echo $LDFLAGS | grep -q fprofile.generate && echo "-fprofile-generate" || echo "-fprofile-use -fprofile-correction")" \
                     -Adefine:ccflags="$CFLAGS" \
                     -Adefine:ldflags="$LDFLAGS" \
                     -Adefine:lddflags="$LDFLAGS"
build      : |
    %make
profile    : |
    TEST_JOBS="%YJOBS%" make test_harness || :
install    : |
    %make_install
check      : |
    # There are still a few failing tests among which the Net-Ping ones which is expected.
    #TEST_JOBS="%YJOBS%" make test_harness
