name        : perl
version     : 5.20.1
release     : 3
source      :
    - http://www.cpan.org/src/5.0/perl-5.20.1.tar.gz : fef10210f9e6f4dc2d190be0aee8e1fa2af664630f1d415868d33eebca26d4b5
license     :
    - Artistic-1.0-Perl
    - GPL-2.0
    - GPL-1.0
    - MIT
summary     : Perl
component   : programming
patterns    :
    - docs:
        - /usr/share/man
description : |
    An interpreted scripting language, known among some as "Unix's Swiss Army Chainsaw".
setup      : |
    sed -i -e "s|BUILD_ZLIB\s*= True|BUILD_ZLIB = False|" \
    -e "s|INCLUDE\s*= ./zlib-src|INCLUDE    = /usr/include|" \
    -e "s|LIB\s*= ./zlib-src|LIB        = /usr/lib|"         \
    cpan/Compress-Raw-Zlib/config.in
    
    # Now configure
    ./Configure -des -Dprefix=/usr\
                     -Dvendorprefix=/usr           \
                     -Dman1dir=/usr/share/man/man1 \
                     -Dman3dir=/usr/share/man/man3 \
                     -Dpager="/usr/bin/less -isR"  \
                     -Duseshrplib
build      : |
    %make
install    : |
    %make_install
