name        : perl
version     : 5.22.1
release     : 6
source     :
    - http://www.cpan.org/src/5.0/perl-5.22.1.tar.gz : 2b475d0849d54c4250e9cba4241b7b7291cffb45dfd083b677ca7b5d38118f27
license     :
    - Artistic-1.0-Perl
    - GPL-2.0
    - GPL-1.0
    - MIT
summary     : Perl
component   : programming
patterns    :
    - docs:
        - /usr/share/man
description : |
    An interpreted scripting language, known among some as "Unix's Swiss Army Chainsaw".
setup      : |
    %patch -p1 < $pkgfiles/security/cve-2016-1238.patch
    export BUILD_ZLIB=False
    export BUILD_BZIP2=0
    
    # Now configure
    ./Configure -des -Dprefix=/usr\
                     -Dvendorprefix=/usr           \
                     -Dman1dir=/usr/share/man/man1 \
                     -Dman3dir=/usr/share/man/man3 \
                     -Dpager="/usr/bin/less -isR"  \
                     -Duseshrplib \
                     -Dusethreads
build      : |
    export BUILD_ZLIB=False
    export BUILD_BZIP2=0
    %make
install    : |
    export BUILD_ZLIB=False
    export BUILD_BZIP2=0
    %make_install
