name       : perl
version    : 5.24.1
release    : 7
source     :
    - http://www.cpan.org/src/5.0/perl-5.24.1.tar.gz : e6c185c9b09bdb3f1b13f678999050c639859a7ef39c8cad418448075f5918af
license    :
    - Artistic-1.0-Perl
    - GPL-2.0
    - GPL-1.0
    - MIT
summary    : Perl
component  : programming
patterns   :
    - docs :
        - /usr/share/man
description: |
    An interpreted scripting language, known among some as "Unix's Swiss Army Chainsaw".
setup      : |
    export BUILD_ZLIB=False
    export BUILD_BZIP2=0

    # Now configure
    ./Configure -des -Dprefix=/usr\
                     -Dvendorprefix=/usr           \
                     -Dman1dir=/usr/share/man/man1 \
                     -Dman3dir=/usr/share/man/man3 \
                     -Dpager="/usr/bin/less -isR"  \
                     -Duseshrplib \
                     -Dusethreads
build      : |
    export BUILD_ZLIB=False
    export BUILD_BZIP2=0
    %make
install    : |
    export BUILD_ZLIB=False
    export BUILD_BZIP2=0
    %make_install
