name       : perl
version    : 5.26.1
release    : 11
source     :
    - https://www.cpan.org/src/5.0/perl-5.26.1.tar.xz : fe8208133e73e47afc3251c08d2c21c5a60160165a8ab8b669c43a420e4ec680
license    :
    - Artistic-1.0-Perl
    - GPL-2.0
    - GPL-1.0
    - MIT
component  : programming
summary    : Perl
description: |
    An interpreted scripting language, known among some as "Unix's Swiss Army Chainsaw".
builddeps  :
    - bzip2-devel
    - gdbm-devel
patterns   :
    - docs :
        - /usr/share/man
setup      : |
    export BUILD_ZLIB=False
    export BUILD_BZIP2=0
    export versionp=`echo ${version} | sed 's:\.[0-9]$::'`
    export archname="x86_64-linux-thread-multi"

    # Changes to the arch (threading for example), require full rebuilds
    # .x releases no longer require rebuilds (5.yy.x)
    ./Configure -des -Dprefix=/usr \
                     -Dvendorprefix=/usr \
                     -Dprivlib=%libdir%/perl5/${versionp} \
                     -Darchlib=%libdir%/perl5/${versionp}/${archname} \
                     -Dsitelib=%libdir%/perl5/site_perl/${versionp} \
                     -Dsitearch=%libdir%/perl5/site_perl/${versionp}/${archname} \
                     -Dvendorlib=%libdir%/perl5/vendor_perl/${versionp} \
                     -Dvendorarch=%libdir%/perl5/vendor_perl/${versionp}/${archname} \
                     -Dscriptdir=/usr/bin \
                     -Dman1dir=/usr/share/man/man1 \
                     -Dman3dir=/usr/share/man/man3 \
                     -Dpager="/usr/bin/less -isR"  \
                     -Duseshrplib \
                     -Dusethreads
build      : |
    export BUILD_ZLIB=False
    export BUILD_BZIP2=0
    %make
install    : |
    export BUILD_ZLIB=False
    export BUILD_BZIP2=0
    %make_install
check      : |
    export BUILD_ZLIB=False
    export BUILD_BZIP2=0

    # There are still a few failing tests among which the Net-Ping ones which is expected.
    #TEST_JOBS="%YJOBS%" make test_harness
